export const ui = {
  fr: {
    subtitle: 'Explorateur interactif — Algèbre & Analyse',
    themeLight: 'Mode clair',
    themeDark: 'Mode sombre',
    openMenu: 'Ouvrir le menu',
    comingSoon: 'A venir',
    home: 'Accueil',
    tabs: ['Visualisation', 'Explication'],
    heroKicker: 'Licence — Double licence Math-Info',
    heroTitleA: 'Voir les maths ',
    heroTitleEm: 'bouger',
    heroSubtitle:
      "Un compagnon interactif pour l'algèbre linéaire, les formes quadratiques, les suites et les séries — chaque notion a sa propre visualisation manipulable.",
    notBuiltYet: 'Ce module sera construit dans une prochaine session.',
    notFound: 'Sujet introuvable.',
    backHome: "← Retour à l'accueil",
    explanationMissing: "Explication à venir pour ce module.",
  },
  en: {
    subtitle: 'Interactive explorer — Algebra & Analysis',
    themeLight: 'Light mode',
    themeDark: 'Dark mode',
    openMenu: 'Open menu',
    comingSoon: 'Coming soon',
    home: 'Home',
    tabs: ['Visualization', 'Explanation'],
    heroKicker: 'Undergraduate — Math-CompSci double major',
    heroTitleA: 'Watch math ',
    heroTitleEm: 'move',
    heroSubtitle:
      'An interactive companion for linear algebra, quadratic forms, sequences, and series — every concept gets its own hands-on visualization.',
    notBuiltYet: 'This module will be built in an upcoming session.',
    notFound: 'Topic not found.',
    backHome: '← Back to home',
    explanationMissing: 'Explanation coming for this module.',
  },
}